define U-Boot/xiguapi-v3-rk3568
  $(U-Boot/rk3568/Default)
  NAME:=Xiguapi V3
  UBOOT_CONFIG:=rk3568-xiguapi-v3
  BUILD_DEVICES:= \
       nlnet_xiguapi-v3
endef



UBOOT_TARGETS := \
  xiguapi-v3-rk3568 \
